name: text_divider
description: This library provides a customizable Flutter widget that makes it easy to display text in the middle of a Divider.
version: 0.0.1
homepage: https://github.com/myConsciousness/divider-with-text

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
